spring:

  rabbitmq:
    # 服务器

    #用户名
    username: guest
    #密码
    password: guest
    # 虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数。比如配2.0，第一次就等10s，第二次就等20s，第三次就等40s
        multiplier: 1


  #静态资源处理
  resources:
    #启动默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存相应时间，单位秒
        max-age: 3600
    chain:
      #资源链启动缓存，默认启动
      cache: true
      #启用资源链，默认禁用
      enabled: true
      #启用压缩资源(gzip,brotli)解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?userUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    hikari:
      #链接池名
      pool-name: DataHikaripC
      #最小空闲链接数
      minimum-idle: 5
      #空闲链接最大存活时间，默认10分钟
      idle-timeout: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认30分钟
      max-lifetime: 1800000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1



mybatis-plus:
  #配置mapper.xml映射位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名（默认是类名
  type-aliases-package: com.fei.pojo

#Mybatis SQL打印（方法接口所在的包，不是Mapper.xml
logging:
  level:
    com.fei.seckill.mapper: debug


  # redis配置
  redis:
    #服务器地址
    host: 127.0.0.1
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms

    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5

